<< comment
#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f clktick.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace clktick.sv --exe clktick_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vclktick.mk Vclktick

# run executable simulation file
obj_dir/Vclktick

comment

#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f f1.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1.sv --exe f1_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1.mk Vf1

# run executable simulation file
obj_dir/Vf1
